### PR TITLE
Improve python conversion scripts

### PR DESCRIPTION
**Pull request by fbarbe00**
Rewrite python scripts from python 2 to python 3, improve formatting, wrap everything around a function that can be used from external python scripts.

### CODE REVIEW

**Review by Hespian — APPROVED** [review]
Looks good to me. Does anyone have an issue with updating these to python3?

**Comment by fbarbe00** [comment]
Python 2 is no longer supported since 2020 ( https://www.python.org/doc/sunset-python-2/ ), and I personally haven't seen any active Python project still using Python 2

**Comment by darrenstrash** [comment]
Updating to Python 3 is fine by me.

**Comment by Hespian** [comment]
Ok, I'm merging this then. Thanks for the PR @fbarbe00

**Pull request merged**
